### ISSUE TITLE
Make QA notebooks results available

### ISSUE THREAD

**Issue by luigilcsilva** [linea-it/pz-compute#115]
@luigilcsilva um pedido especial da direção pra vc:
 
Executar todos os notebooks que vc já preparou até hj, exportar uma versão deles em HTML e colocá-los visíveis em algum lugar. Sugestão: use o seu diretório public_html da home.   

- [x] QA DES DR2 small
- [x] QA DP0.2 object 
- [x] tutoriais hipscat / lsdb
- [x] investigação duplicates
- [x] outros que eu tenha esquecido aqui :)  

Comopartilha com o @luiz-nicolaci o link para os notebooks exportados em HTML para sua apreciação.

**Comment by gschwend** [comment]
@luigilcsilva ontem comentei esse problema com o Carlos e ele disse que é possível criar um diretório dentro do `public_html` que seja protegigo por senha. Vamos investigar essa possibilidade.

**Comment by luigilcsilva** [comment]
@gschwend Todos os notebooks já podem ser acessados [aqui](https://dev.linea.org.br/~luigi.silva/). A senha para os arquivos protegidos foi enviada na conversa privada no Slack em 13/11/2024 (quarta-feira).
