### ISSUE TITLE
Input data QA notebooks 

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-compute#3]
Add quality assessment notebooks to characterize PZ Compute input data.   

Content suggestion for the notebook: 

### Local properties - 1 sample file randomy selected from `/lustre/t1/cl/lsst/dp0.2` (temporary: `/home/julia/photoz/qa-pz-compute/skinny_tables`): (as an exercise, using DES DR2 data) 
 
- [x] Summary statistics of selected columns (e.g. using Pandas Dataframe method)
- [x] Spatial distribution  (density) 
- [x] 6-band magnitude distributions 
- [x] 6-band magnitude error 
- [x] 6-band magnitude versus error (scatter or density)
- [x] CMDs
- [x] color-color diagrams
- [x] redshift plots (in case of simulations) 

### Global properties: (using LSST DP0.2 to test)  
(loop over the files, extract info as arrays, combine arrays to make global plots)
- [x] Summary statistics of selected columns (e.g. using Pandas Dataframe method)
- [x] Spatial distribution  (density) 
- [x] 6-band magnitude distributions 
- [x] 6-band magnitude error 
- [x] 6-band magnitude versus error (scatter or density)
- [x] CMDs
- [x] color-color diagrams
- [x] redshift plots (in case of simulations) 

### Region-dependent properties (maps): 
- TBD (on a new issue)

**Comment by luigilcsilva** [comment]
The first part of this issue is done (Local Properties). The second part (Global Properties) is still in progress. When I finish the "QA report LSST DP0.2 full [#82](https://github.com/linea-it/pz-compute/issues/82)" issue, this issue will also be finished.
