### ISSUE TITLE
Create script to run RAIL in command line mode on cluster Apollo

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-compute#4]

**Comment by hdante** [comment]
Initial implementation available in branch rail-scripts. The scripts are called `rail-estimate` and `rail-train`. Copy pasting the help messages from the scripts:

	$ ./rail-estimate --help
	Generate photo-z estimate tables from raw data.

	Usage:
	    rail-estimate [options] [--] <input> <output>
	    rail-estimate -h | --help
	    rail-estimate --version

	Options:
	    -h --help   Show help text.
	    --version   Show version.
	    -a <name>, --algorithm=<name>  Select estimation algorithm
		                           [default: fzboost].
	    -b <bins>, --bins=<bins>       Set number of bins (columns) in the resulting
		                           tables [default: 301].
	    -g <group>, --group=<group>    For HDF5 input, sets the group name (section)
		                           where input data is stored [default: ]
	    --column-template=<template>   Set the names of the input columns
		                           [default: mag_{band}]
	    --column-template-error=<template-error>  Set the names of the input error
		                                      columns [default: magerr_{band}]


	Available algorithms: bpz, fzboost


	$ ./rail-train --help
	Train photo-z algorithms with reference data.

	Usage:
	    rail-train [options] [--] <input> [<output>]
	    rail-train -h | --help
	    rail-train --version

	Options:
	    -h --help   Show help text.
	    --version   Show version.
	    -a <name>, --algorithm=<name>  Select estimation algorithm
		                           [default: fzboost].
	    -b <bins>, --bins=<bins>       Set number of bins (columns) in the resulting
		                           tables [default: 301].
	    -g <group>, --group=<group>    For HDF5 input, sets the group name (section)
		                           where input data is stored [default: ]
	    --column-template=<template>   Set the names of the input columns
		                           [default: mag_{band}]
	    --column-template-error=<template-error>  Set the names of the input error
		                                      columns [default: magerr_{band}]


	Available algorithms: bpz, fzboost

	The generated output file contains the resulting trained state and is in Python
	pickle format. The default output name is "estimator_<algorithm>.pkl".

Link to the scripts:

- https://github.com/linea-it/pz-compute/blob/rail-scripts/rail_scripts/rail-estimate
- https://github.com/linea-it/pz-compute/blob/rail-scripts/rail_scripts/rail-train

There are some known issues related with inconsistent file format handling within the different RAIL libraries.

A quick start guide was written and is available as documentation: [Getting started with the rail-estimate script](https://github.com/linea-it/pz-compute/blob/rail-scripts/doc/rail-estimate-getting-started.md)
